### PR TITLE
Fix config parser compilation

### PR DESCRIPTION
**Pull request by AndersLazis**
Fix config parser compilation

### CODE REVIEW

**Review by cmenke42 — CHANGES_REQUESTED** [review]
➜ /workspaces/WebserV/webserv (fix_config_parser_compilation) $ valgrind --leak-check=full --show-leak-kinds=all ./test_config_parser.out 
```
==5422== Memcheck, a memory error detector
==5422== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==5422== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==5422== Command: ./test_config_parser.out
==5422== 
CONFIG PARSER: Error: Configuration file must consist at least one server block
==5422== 
==5422== HEAP SUMMARY:
==5422==     in use at exit: 472 bytes in 1 blocks
==5422==   total heap usage: 24 allocs, 23 frees, 95,579 bytes allocated
==5422== 
==5422== 472 bytes in 1 blocks are still reachable in loss record 1 of 1
==5422==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==5422==    by 0x4AD392D: __fopen_internal (iofopen.c:65)
==5422==    by 0x4AD392D: fopen@@GLIBC_2.2.5 (iofopen.c:86)
==5422==    by 0x1162AF: ConfigParser::checkConfigFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (ConfigParserUtils.cpp:11)
==5422==    by 0x10DA54: ConfigParser::parseConfig(int, char**) (ConfigParser.cpp:58)
==5422==    by 0x10C2AD: main (test_config_parser.cpp:62)
==5422== 
==5422== LEAK SUMMARY:
==5422==    definitely lost: 0 bytes in 0 blocks
==5422==    indirectly lost: 0 bytes in 0 blocks
==5422==      possibly lost: 0 bytes in 0 blocks
==5422==    still reachable: 472 bytes in 1 blocks
==5422==         suppressed: 0 bytes in 0 blocks
==5422== 
==5422== For lists of detected and suppressed errors, rerun with: -s
==5422== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```






FILE:
```
timeout: 20 ; 
max_clients: 100;						
max_size_of_file: 1000000;	
```

**Comment by AndersLazis** [comment]
Screen Shot 2023-11-21 at 10 25 08 PM
Thanks Carlos! I fixed it

**Review by cmenke42 — CHANGES_REQUESTED** [review]
➜ /workspaces/WebserV/webserv (fix_config_parser_compilation) $ valgrind --leak-check=full --show-leak-kinds=all ./test_config_parser.out 
==18595== Memcheck, a memory error detector
==18595== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==18595== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==18595== Command: ./test_config_parser.out
==18595== 
CONFIG PARSER: Error: Empty configuration file
==18595== 
==18595== HEAP SUMMARY:
==18595==     in use at exit: 472 bytes in 1 blocks
==18595==   total heap usage: 21 allocs, 20 frees, 86,752 bytes allocated
==18595== 
==18595== 472 bytes in 1 blocks are still reachable in loss record 1 of 1
==18595==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==18595==    by 0x4AD392D: __fopen_internal (iofopen.c:65)
==18595==    by 0x4AD392D: fopen@@GLIBC_2.2.5 (iofopen.c:86)
==18595==    by 0x1162AF: ConfigParser::checkConfigFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (ConfigParserUtils.cpp:11)
==18595==    by 0x10DA54: ConfigParser::parseConfig(int, char**) (ConfigParser.cpp:58)
==18595==    by 0x10C2AD: main (test_config_parser.cpp:62)
==18595== 
==18595== LEAK SUMMARY:
==18595==    definitely lost: 0 bytes in 0 blocks
==18595==    indirectly lost: 0 bytes in 0 blocks
==18595==      possibly lost: 0 bytes in 0 blocks
==18595==    still reachable: 472 bytes in 1 blocks
==18595==         suppressed: 0 bytes in 0 blocks
==18595== 
==18595== For lists of detected and suppressed errors, rerun with: -s
==18595== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)


Empty file as input

**Comment by AndersLazis** [comment]
> valgrind --leak-check=full --show-leak-kinds=all ./test_config_parser.out

Thanks bro! Sorry that I didn't  notice that. I fixed it.

**Review by cmenke42 — CHANGES_REQUESTED** [review]
already discussed

**Pull request closed without merging**
